version: "3.9"

services:
  k8s-dbi:
    container_name: k8s-dbi
    build:
      context: .
      dockerfile: Dockerfile
    image: khacdatdo/k8s-dbi:v1.0.0
    command:
      - /bin/bash
      - -c
      - |
        mysqldump --version
        pg_dump --version
        mongodump --version
