name: k8s-dbi-postgres
services:
  postgres:
    image: postgres:17.2-alpine
    container_name: k8s-dbi-postgres-db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: abcd1234
  k8s-dbi:
    container_name: k8s-dbi-postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: khacdatdo/k8s-dbi:postgres
    environment:
      DB_HOST: k8s-dbi-postgres-db
      DB_USER: root
      DB_PASS: abcd1234
      DB_NAME: demo
      BACKUP_PASSWORD: changeme
      S3_URL: https://s3.example.com
      ACCESS_KEY: access_key_example
      SECRET_KEY: secret_key_example
      S3_BUCKET: demo-bucket
      S3_PATH: demo
    volumes:
      - ./.data:/backup
    depends_on:
      - postgres
